import { useState, useMemo } from 'react';
import Icon from '../components/ui/Icon';
import { BarChart, ChartCard, LineChart } from '../components/charts';
import Button from '../components/ui/Button';
import { ErrorState, LoadingState } from '../components/ui/LoadState';
import PageHeader from '../components/ui/PageHeader';
import StatCard from '../components/ui/StatCard';
import { useBusinessData } from '../api/resources';
import { currency, date, indexById, lastMonthsSeries, number, status } from '../utils/formatters';

const REPORT_TYPES = [
  { key: 'Sales Report', icon: 'sales' },
  { key: 'Revenue Report', icon: 'revenue' },
  { key: 'Expense Report', icon: 'expenses' },
  { key: 'Inventory Report', icon: 'inventory' },
  { key: 'Customer Report', icon: 'customers' },
];

/** Build a simple print window from an HTML string */
function openPrintWindow(html) {
  const win = window.open('', '_blank', 'width=900,height=700');
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

/** Shared print-page wrapper */
function printTemplate(title, bodyHtml) {
  return `<!DOCTYPE html><html>
  <head>
    <title>${title}</title>
    <style>
      body { font-family: Inter, system-ui, sans-serif; color: #111; padding: 40px; font-size: 14px; }
      h1   { font-size: 22px; margin: 0 0 4px; }
      .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
      th { text-align: left; padding: 8px 10px; font-size: 11px; color: #888;
           text-transform: uppercase; border-bottom: 2px solid #eee; }
      td { padding: 8px 10px; border-bottom: 1px solid #f0f0f0; }
      .footer { margin-top: 32px; font-size: 12px; color: #aaa; text-align: center; }
    </style>
  </head>
  <body>
    <h1>${title}</h1>
    <div class="meta">Generated by SmartBiz &bull; ${new Date().toLocaleDateString()}</div>
    ${bodyHtml}
    <div class="footer">SmartBiz &bull; ${new Date().toLocaleDateString()}</div>
  </body></html>`;
}

export default function Reports() {
  const { data, loading, error, reload } = useBusinessData();
  const [selectedReport, setSelectedReport] = useState('Sales Report');
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');

  // ── All hooks BEFORE any early returns ───────────────────────────────────

  const filteredSales = useMemo(() => {
    if (!data?.sales) return [];
    return data.sales.filter((sale) => {
      const d = new Date(sale.saleDate);
      if (fromDate && d < new Date(fromDate)) return false;
      if (toDate && d > new Date(toDate)) return false;
      return true;
    });
  }, [data?.sales, fromDate, toDate]);

  const filteredExpenses = useMemo(() => {
    if (!data?.expenses) return [];
    return data.expenses.filter((exp) => {
      const d = new Date(exp.expenseDate);
      if (fromDate && d < new Date(fromDate)) return false;
      if (toDate && d > new Date(toDate)) return false;
      return true;
    });
  }, [data?.expenses, fromDate, toDate]);

  const revenue = useMemo(() => lastMonthsSeries(filteredSales, 'saleDate', 'totalAmount'), [filteredSales]);
  const expenses = useMemo(() => lastMonthsSeries(filteredExpenses, 'expenseDate', 'amount'), [filteredExpenses]);

  const totalSales = useMemo(() => filteredSales.reduce((s, x) => s + Number(x.totalAmount || 0), 0), [filteredSales]);
  const totalExpenses = useMemo(() => filteredExpenses.reduce((s, x) => s + Number(x.amount || 0), 0), [filteredExpenses]);
  const profit = totalSales - totalExpenses;
  const totalProducts = data?.products?.length || 0;

  const pendingInvoices = useMemo(() => data?.invoices?.filter(i => i.status === 'PENDING').length || 0, [data?.invoices]);
  const paidInvoices = useMemo(() => data?.invoices?.filter(i => i.status === 'PAID').length || 0, [data?.invoices]);
  const customerById = useMemo(() => indexById(data?.customers || []), [data?.customers]);

  // ── Early returns AFTER all hooks ─────────────────────────────────────────
  if (loading) return <LoadingState message="Loading reports..." />;
  if (error) return <ErrorState message={error} onRetry={reload} />;

  // ── Print helpers ─────────────────────────────────────────────────────────

  const handlePrintSales = () => {
    const rows = filteredSales.map(s => {
      const custName = customerById[s.customerId]?.fullName || `Customer #${s.customerId || '-'}`;
      return `
      <tr>
        <td>#${s.saleId ?? s.id ?? '—'}</td>
        <td>${custName}</td>
        <td>${date(s.saleDate)}</td>
        <td>${status(s.paymentMethod ?? '')}</td>
        <td>${status(s.status ?? '')}</td>
        <td style="text-align:right">${currency(s.totalAmount)}</td>
      </tr>`;
    }).join('');
    openPrintWindow(printTemplate('Sales Report', `
      <table>
        <thead><tr>
          <th style="width: 12%">Sale ID</th>
          <th style="width: 20%">Customer</th>
          <th style="width: 18%">Date</th>
          <th style="width: 18%">Payment</th>
          <th style="width: 15%">Status</th>
          <th style="width: 17%; text-align: right">Total</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="6">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintExpenses = () => {
    const rows = filteredExpenses.map(e => `
      <tr>
        <td>${e.notes ?? '—'}</td>
        <td>${e.category ?? '—'}</td>
        <td>${date(e.expenseDate)}</td>
        <td style="text-align:right">${currency(e.amount)}</td>
      </tr>`).join('');
    openPrintWindow(printTemplate('Expense Report', `
      <table>
        <thead><tr>
          <th style="width: 40%">Description</th>
          <th style="width: 20%">Category</th>
          <th style="width: 20%">Date</th>
          <th style="width: 20%; text-align: right">Amount</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="4">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintInventory = () => {
    const rows = (data.products || []).map(p => {
      const qty = Number(p.stockQuantity || 0);
      const stockLabel = qty <= 0 ? 'Out of Stock' : qty <= 10 ? 'Low Stock' : 'In Stock';
      return `
      <tr>
        <td>${p.productName ?? '—'}</td>
        <td>${p.category ?? '—'}</td>
        <td style="text-align:right">${number(p.stockQuantity)}</td>
        <td style="text-align:right">${currency(p.unitPrice ?? 0)}</td>
        <td>${stockLabel}</td>
      </tr>`;
    }).join('');
    openPrintWindow(printTemplate('Inventory Report', `
      <table>
        <thead><tr>
          <th style="width: 35%">Product</th>
          <th style="width: 20%">Category</th>
          <th style="width: 15%; text-align: right">Stock Qty</th>
          <th style="width: 15%; text-align: right">Price</th>
          <th style="width: 15%">Status</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="5">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintCustomers = () => {
    const rows = (data.customers || []).map(c => `
      <tr>
        <td>${c.fullName ?? '—'}</td>
        <td>${c.email ?? '—'}</td>
        <td>${c.phone ?? '—'}</td>
        <td>${c.address ?? '—'}</td>
      </tr>`).join('');
    openPrintWindow(printTemplate('Customer Report', `
      <table>
        <thead><tr>
          <th style="width: 25%">Name</th>
          <th style="width: 25%">Email</th>
          <th style="width: 20%">Phone</th>
          <th style="width: 30%">Address</th>
        </tr></thead>
        <tbody>${rows || '<tr><td colspan="4">No records</td></tr>'}</tbody>
      </table>`));
  };

  const handlePrintRevenue = () => {
    openPrintWindow(printTemplate('Revenue Report', `
      <table>
        <thead><tr>
          <th style="width: 40%">Period</th>
          <th style="width: 20%; text-align: right">Total Sales</th>
          <th style="width: 20%; text-align: right">Total Expenses</th>
          <th style="width: 20%; text-align: right">Profit</th>
        </tr></thead>
        <tbody>
          <tr>
            <td>${fromDate || 'All time'} – ${toDate || 'Now'}</td>
            <td style="text-align:right">${currency(totalSales)}</td>
            <td style="text-align:right">${currency(totalExpenses)}</td>
            <td style="text-align:right;font-weight:700;color:${profit >= 0 ? 'green' : 'red'}">${currency(profit)}</td>
          </tr>
        </tbody>
      </table>`));
  };

  const printHandlers = {
    'Sales Report': handlePrintSales,
    'Revenue Report': handlePrintRevenue,
    'Expense Report': handlePrintExpenses,
    'Inventory Report': handlePrintInventory,
    'Customer Report': handlePrintCustomers,
  };

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="flex flex-col gap-[22px] max-w-[1600px] mx-auto px-[15px]">
      <PageHeader
        eyebrow="Reports"
        title="Reporting Dashboard"
        description="Generate and print reports from live SmartBiz records."
        actions={(
          <Button variant="primary" onClick={printHandlers[selectedReport]}>
            <Icon name="print" size={17} className="mr-[6px]" /> Print {selectedReport}
          </Button>
        )}
      />

      {/* Report Type Selector */}
      <section className="report-type-grid grid grid-cols-5 gap-4 max-[1180px]:grid-cols-3 max-[860px]:grid-cols-1">
        {REPORT_TYPES.map(({ key, icon }) => (
          <button
            key={key}
            type="button"
            onClick={() => setSelectedReport(key)}
            className={`min-h-[72px] border rounded-[var(--radius)] shadow-[var(--shadow)] cursor-pointer font-extrabold transition-colors duration-200 ${
              selectedReport === key
                ? 'bg-[var(--blue-soft)] text-[var(--blue)] border-[var(--blue)]'
                : 'bg-[var(--surface)] text-[var(--text)] border-[var(--border)]'
            }`}
          >
            <span className="text-[22px] flex justify-center mb-[6px]">
              <Icon name={icon} size={24} />
            </span>
            {key}
          </button>
        ))}
      </section>

      {/* Date range filter */}
      <div className="report-toolbar flex gap-3 flex-wrap">
        <label className="flex items-center gap-2 bg-[var(--surface)] text-[var(--text)] border border-[var(--border)] rounded-[12px] py-2.5 px-3">
          From
          <input
            type="date"
            value={fromDate}
            onChange={(e) => setFromDate(e.target.value)}
            className="border border-[var(--border)] rounded-[10px] bg-[var(--surface)] text-[var(--text)] py-[9px] px-[10px] outline-0"
          />
        </label>
        <label className="flex items-center gap-2 bg-[var(--surface)] text-[var(--text)] border border-[var(--border)] rounded-[12px] py-2.5 px-3">
          To
          <input
            type="date"
            value={toDate}
            onChange={(e) => setToDate(e.target.value)}
            className="border border-[var(--border)] rounded-[10px] bg-[var(--surface)] text-[var(--text)] py-[9px] px-[10px] outline-0"
          />
        </label>
        {(fromDate || toDate) && (
          <button
            type="button"
            className="app-button ghost"
            onClick={() => { setFromDate(''); setToDate(''); }}
          >
            <Icon name="close" size={15} /> Clear filter
          </button>
        )}
      </div>

      {/* ── SALES REPORT ─────────────────────────────────────────────── */}
      {selectedReport === 'Sales Report' && (
        <>
          <section className="grid grid-cols-3 gap-4 max-[860px]:grid-cols-1">
            <StatCard label="Total Sales" value={currency(totalSales)} growth="Live" icon="revenue" />
            <StatCard label="Transactions" value={number(filteredSales.length)} growth="Live" icon="revenue" />
            <StatCard
              label="Avg. Sale Value"
              value={currency(filteredSales.length ? totalSales / filteredSales.length : 0)}
              growth="Live"
              icon="revenue"
            />
          </section>

          <section className="grid grid-cols-2 gap-4 max-[1180px]:grid-cols-1">
            <ChartCard title="Sales Over Time" subtitle="Monthly totals">
              <LineChart data={revenue.values} labels={revenue.labels} />
            </ChartCard>
            <ChartCard title="Revenue vs Expenses" subtitle="Comparison by month">
              <BarChart revenue={revenue.raw} expenses={expenses.raw} labels={revenue.labels} />
            </ChartCard>
          </section>

          <section className="bg-[var(--surface)] border border-[var(--border)] rounded-[var(--radius)] shadow-[var(--shadow)] p-5">
            <h3 className="m-0 mb-4 text-[16px] font-bold text-[var(--text)]">Sales Transactions</h3>
            {filteredSales.length ? (
              <div className="overflow-x-auto">
                <table className="w-full border-collapse min-w-[760px]">
                  <thead>
                    <tr className="border-b-2 border-[var(--border)]">
                      <th className="w-[12%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Sale ID</th>
                      <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Customer</th>
                      <th className="w-[18%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Date</th>
                      <th className="w-[18%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Payment Method</th>
                      <th className="w-[15%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Status</th>
                      <th className="w-[17%] py-3.5 px-3 text-right text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Total Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredSales.map((sale, idx) => {
                      const custName = customerById[sale.customerId]?.fullName || `Customer #${sale.customerId || '-'}`;
                      const isLast = idx === filteredSales.length - 1;
                      const borderClass = isLast ? '' : 'border-b border-[var(--border)]';
                      const statusLower = sale.status?.toLowerCase() || '';
                      const statusClass = 
                        ['paid', 'completed', 'in-stock'].includes(statusLower)
                          ? 'bg-[var(--green-soft)] text-[var(--green)]'
                          : ['pending', 'low-stock'].includes(statusLower)
                          ? 'bg-[var(--orange-soft)] text-[#b76b00]'
                          : ['overdue', 'out-of-stock', 'refunded'].includes(statusLower)
                          ? 'bg-[var(--red-soft)] text-[var(--red)]'
                          : 'bg-[var(--blue-soft)] text-[var(--blue)]';
                      return (
                        <tr key={sale.id ?? sale.saleId}>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>#{sale.saleId ?? sale.id}</td>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] font-medium ${borderClass}`}>{custName}</td>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{date(sale.saleDate)}</td>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{status(sale.paymentMethod ?? '')}</td>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>
                            <span className={`inline-flex items-center min-h-[24px] px-[9px] rounded-full text-[12px] font-extrabold ${statusClass}`}>
                              {status(sale.status ?? '')}
                            </span>
                          </td>
                          <td className={`py-3.5 px-3 text-right text-[14px] text-[var(--text)] font-bold ${borderClass}`}>{currency(sale.totalAmount)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="text-[var(--muted)] m-0">No sales in the selected date range.</p>
            )}
          </section>
        </>
      )}

      {/* ── REVENUE REPORT ───────────────────────────────────────────── */}
      {selectedReport === 'Revenue Report' && (
        <>
          <section className="grid grid-cols-3 gap-4 max-[860px]:grid-cols-1">
            <StatCard label="Total Revenue" value={currency(totalSales)} growth="Live" icon="revenue" />
            <StatCard label="Total Expenses" value={currency(totalExpenses)} growth="Live" icon="expenses" />
            <StatCard label="Net Profit" value={currency(profit)} growth={profit >= 0 ? 'Profitable' : 'Loss'} icon="revenue" />
            <StatCard label="Paid Invoices" value={number(paidInvoices)} growth="Live" icon="invoice" />
            <StatCard label="Pending Invoices" value={number(pendingInvoices)} growth="Live" icon="invoice" />
            <StatCard label="Products Listed" value={number(totalProducts)} growth="Live" icon="inventory" />
          </section>

          <section className="grid grid-cols-2 gap-4 max-[1180px]:grid-cols-1">
            <ChartCard title="Revenue Trend" subtitle="Monthly sales totals">
              <LineChart data={revenue.values} labels={revenue.labels} />
            </ChartCard>
            <ChartCard title="Revenue vs Expenses" subtitle="Side-by-side monthly view">
              <BarChart revenue={revenue.raw} expenses={expenses.raw} labels={revenue.labels} />
            </ChartCard>
          </section>

          <section className="bg-[var(--surface)] border border-[var(--border)] rounded-[var(--radius)] shadow-[var(--shadow)] p-5">
            <h3 className="m-0 mb-4 text-[16px] font-bold text-[var(--text)]">Invoice Summary</h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse min-w-[760px]">
                <thead>
                  <tr className="border-b-2 border-[var(--border)]">
                    <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Invoice No.</th>
                    <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Issue Date</th>
                    <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Due Date</th>
                    <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Status</th>
                    <th className="w-[20%] py-3.5 px-3 text-right text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {data.invoices?.map((inv, idx) => {
                    const isLast = idx === (data.invoices?.length || 0) - 1;
                    const borderClass = isLast ? '' : 'border-b border-[var(--border)]';
                    const statusLower = inv.status?.toLowerCase() || '';
                    const statusClass = 
                      ['paid', 'completed', 'in-stock'].includes(statusLower)
                        ? 'bg-[var(--green-soft)] text-[var(--green)]'
                        : ['pending', 'low-stock'].includes(statusLower)
                        ? 'bg-[var(--orange-soft)] text-[#b76b00]'
                        : ['overdue', 'out-of-stock', 'refunded'].includes(statusLower)
                        ? 'bg-[var(--red-soft)] text-[var(--red)]'
                        : 'bg-[var(--blue-soft)] text-[var(--blue)]';
                    return (
                      <tr key={inv.id}>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{inv.invoiceNumber || `INV-${inv.id}`}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{date(inv.issueDate)}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{date(inv.dueDate)}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>
                          <span className={`inline-flex items-center min-h-[24px] px-[9px] rounded-full text-[12px] font-extrabold ${statusClass}`}>
                            {status(inv.status)}
                          </span>
                        </td>
                        <td className={`py-3.5 px-3 text-right text-[14px] text-[var(--text)] font-bold ${borderClass}`}>{currency(inv.totalAmount)}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}

      {/* ── EXPENSE REPORT ───────────────────────────────────────────── */}
      {selectedReport === 'Expense Report' && (
        <>
          <section className="grid grid-cols-3 gap-4 max-[860px]:grid-cols-1">
            <StatCard label="Total Expenses" value={currency(totalExpenses)} growth="Live" icon="expenses" />
            <StatCard label="No. of Expenses" value={number(filteredExpenses.length)} growth="Live" icon="expenses" />
            <StatCard
              label="Avg. Expense"
              value={currency(filteredExpenses.length ? totalExpenses / filteredExpenses.length : 0)}
              growth="Live"
              icon="expenses"
            />
          </section>

          <section className="grid grid-cols-2 gap-4 max-[1180px]:grid-cols-1">
            <ChartCard title="Expenses Over Time" subtitle="Monthly totals">
              <LineChart data={expenses.values} labels={expenses.labels} />
            </ChartCard>
            <ChartCard title="Revenue vs Expenses" subtitle="Comparison">
              <BarChart revenue={revenue.raw} expenses={expenses.raw} labels={revenue.labels} />
            </ChartCard>
          </section>

          <section className="bg-[var(--surface)] border border-[var(--border)] rounded-[var(--radius)] shadow-[var(--shadow)] p-5">
            <h3 className="m-0 mb-4 text-[16px] font-bold text-[var(--text)]">Expense Records</h3>
            {filteredExpenses.length ? (
              <div className="overflow-x-auto">
                <table className="w-full border-collapse min-w-[760px]">
                  <thead>
                    <tr className="border-b-2 border-[var(--border)]">
                      <th className="w-[40%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Description</th>
                      <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Category</th>
                      <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Date</th>
                      <th className="w-[20%] py-3.5 px-3 text-right text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredExpenses.map((exp, idx) => {
                      const isLast = idx === filteredExpenses.length - 1;
                      const borderClass = isLast ? '' : 'border-b border-[var(--border)]';
                      return (
                        <tr key={exp.id}>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{exp.notes ?? '—'}</td>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{exp.category ?? '—'}</td>
                          <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{date(exp.expenseDate)}</td>
                          <td className={`py-3.5 px-3 text-right text-[14px] text-[var(--text)] font-bold ${borderClass}`}>{currency(exp.amount)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="text-[var(--muted)] m-0">No expenses in the selected date range.</p>
            )}
          </section>
        </>
      )}

      {/* ── INVENTORY REPORT ─────────────────────────────────────────── */}
      {selectedReport === 'Inventory Report' && (
        <>
          <section className="grid grid-cols-3 gap-4 max-[860px]:grid-cols-1">
            <StatCard label="Total Products" value={number(totalProducts)} growth="Live" icon="inventory" />
            <StatCard
              label="Low Stock Items"
              value={number(data.products?.filter(p => Number(p.stockQuantity) > 0 && Number(p.stockQuantity) <= 10).length || 0)}
              growth="Watch"
              icon="inventory"
            />
            <StatCard
              label="Out of Stock"
              value={number(data.products?.filter(p => Number(p.stockQuantity) <= 0).length || 0)}
              growth="Alert"
              icon="inventory"
            />
          </section>

          <section className="bg-[var(--surface)] border border-[var(--border)] rounded-[var(--radius)] shadow-[var(--shadow)] p-5">
            <h3 className="m-0 mb-4 text-[16px] font-bold text-[var(--text)]">Inventory Status</h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse min-w-[760px]">
                <thead>
                  <tr className="border-b-2 border-[var(--border)]">
                    <th className="w-[25%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Product Name</th>
                    <th className="w-[15%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Category</th>
                    <th className="w-[20%] py-3.5 px-3 text-right text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Stock Qty</th>
                    <th className="w-[20%] py-3.5 px-3 text-right text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Selling Price</th>
                    <th className="w-[20%] py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {data.products?.map((product, idx) => {
                    const qty = Number(product.stockQuantity || 0);
                    const stockStatus = qty <= 0 ? 'out-of-stock' : qty <= 10 ? 'low-stock' : 'in-stock';
                    const stockLabel = qty <= 0 ? 'Out of Stock' : qty <= 10 ? 'Low Stock' : 'In Stock';
                    const isLast = idx === (data.products?.length || 0) - 1;
                    const borderClass = isLast ? '' : 'border-b border-[var(--border)]';
                    const statusClass = 
                      stockStatus === 'in-stock'
                        ? 'bg-[var(--green-soft)] text-[var(--green)]'
                        : stockStatus === 'low-stock'
                        ? 'bg-[var(--orange-soft)] text-[#b76b00]'
                        : 'bg-[var(--red-soft)] text-[var(--red)]';
                    return (
                      <tr key={product.id}>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] font-medium ${borderClass}`}>{product.productName}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{product.category ?? '—'}</td>
                        <td className={`py-3.5 px-3 text-right text-[14px] text-[var(--text)] ${borderClass}`}>{number(qty)}</td>
                        <td className={`py-3.5 px-3 text-right text-[14px] text-[var(--text)] ${borderClass}`}>{currency(product.unitPrice ?? 0)}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>
                          <span className={`inline-flex items-center min-h-[24px] px-[9px] rounded-full text-[12px] font-extrabold ${statusClass}`}>
                            {stockLabel}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}

      {/* ── CUSTOMER REPORT ──────────────────────────────────────────── */}
      {selectedReport === 'Customer Report' && (
        <>
          <section className="grid grid-cols-3 gap-4 max-[860px]:grid-cols-1">
            <StatCard label="Total Customers" value={number(data.customers?.length || 0)} growth="Live" icon="revenue" />
            <StatCard label="Paid Invoices" value={number(paidInvoices)} growth="Live" icon="invoice" />
            <StatCard label="Total Revenue" value={currency(totalSales)} growth="Live" icon="revenue" />
          </section>

          <section className="bg-[var(--surface)] border border-[var(--border)] rounded-[var(--radius)] shadow-[var(--shadow)] p-5">
            <h3 className="m-0 mb-4 text-[16px] font-bold text-[var(--text)]">Customer Directory</h3>
            <div className="overflow-x-auto">
              <table className="w-full border-collapse min-w-[760px]">
                <thead>
                  <tr className="border-b-2 border-[var(--border)]">
                    <th className="py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Full Name</th>
                    <th className="py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Email</th>
                    <th className="py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Phone</th>
                    <th className="py-3.5 px-3 text-left text-[12px] font-semibold text-[var(--muted)] uppercase tracking-wider bg-[var(--surface-soft)]">Address</th>
                  </tr>
                </thead>
                <tbody>
                  {data.customers?.map((customer, idx) => {
                    const isLast = idx === (data.customers?.length || 0) - 1;
                    const borderClass = isLast ? '' : 'border-b border-[var(--border)]';
                    return (
                      <tr key={customer.id}>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] font-medium ${borderClass}`}>{customer.fullName ?? '—'}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{customer.email ?? '—'}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--text)] ${borderClass}`}>{customer.phone ?? '—'}</td>
                        <td className={`py-3.5 px-3 text-left text-[14px] text-[var(--muted)] ${borderClass}`}>{customer.address ?? '—'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}
    </div>
  );
}
